services:
  amateur_pt:
    environment:
      - DISPLAY=novnc:0.0
    volumes:
      - ../.:/root/AmateurPolicyImitation
    command: bash -c "tail -f /dev/null"
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  novnc:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=6000
      - DISPLAY_HEIGHT=3000 #need to adjust based off height and width of your screen, going for bigger values is typically recommended.